id: IC89069CA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:24:43+00:00'
last_modified: '2022-06-08T18:09:36.857493+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9561
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    48AE:
      image_group_id: I1KG9578
      title: Volume 1 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      total_pages: 850
      order: 1
      base_file: 48AE.txt
    EBA1:
      image_group_id: I1KG9579
      title: Volume 2 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      total_pages: 821
      order: 2
      base_file: EBA1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
