id: P008062
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9561
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  volumes:
    c84fa0d491154621b047a809deca7caf:
      image_group_id: I1KG9578
      title: ''
      volume_number: 1
      total_pages: 850
    65d2ffc1bf3a4ca582ab274517581486:
      image_group_id: I1KG9579
      title: ''
      volume_number: 2
      total_pages: 821
ebook_metadata:
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  sku: P008062
  cover: cover.jpg
  layers:
  - pagination
