id: opecha:P008062
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9561
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  volume:
    1cc276cc7a854dc59744f70a6416fb0d:
      image_group_id: I1KG9578
      title: Volume 1 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      volume_number: 1
      total_pages: 850
    b11b89d207354665a64a53d483f6ca95:
      image_group_id: I1KG9579
      title: Volume 2 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      volume_number: 2
      total_pages: 821
  author: ''
ebook_metadata:
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  sku: P008062
  cover: cover.jpg
  layers:
  - pagination
