id: P008062
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:51.321999
source_metadata:
  id: bdr:W1KG9561
  title: གསུང་འབུམ། དབྱངས་ཅན་དགའ་བའི་བློ་གྲོས། （སྐུ་འབུམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  volumes:
    1cc276cc7a854dc59744f70a6416fb0d:
      image_group_id: I1KG9578
      title: Volume 1 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      volume_number: 1
      total_pages: 850
      base_file: v001.txt
    b11b89d207354665a64a53d483f6ca95:
      image_group_id: I1KG9579
      title: Volume 2 of gsung 'bum/_dbyangs can dga' ba'i blo gros/ (sku 'bum par
        ma'i par shus/)
      volume_number: 2
      total_pages: 821
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
